# Generated by Django 4.2.7 on 2023-12-24 21:54

import api.models.variant
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_cartitem_product_cartitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=api.models.variant.get_file_path),
        ),
        migrations.AddField(
            model_name='variant',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, editable=False, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
